language: perl
perl:
    - "5.20"
    - "5.18"
    - "5.16"
before_script:
    - sudo touch /etc/make.conf
    - sudo chmod 666 /etc/make.conf
    - echo "PORTDIR=/usr/portage" >> /etc/make.conf
    - echo "PORTDIR_OVERLAY=/usr/local/portage" >> /etc/make.conf
    - echo 'USE="perl -python"' >> /etc/make.conf
    - sudo mkdir /usr/portage /usr/local/portage
    - sudo chown $USER:$USER /usr/portage /usr/local/portage
    - wget "http://distfiles.gentoo.org/snapshots/portage-latest.tar.xz"
    - tar xJf portage-latest.tar.xz -C /usr/
after_success:
    - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
    - cover -test -report coveralls
#notifications:
#    irc: "chat.freenode.net#gentoo-perl"
#    on_success: change
#    on_failure: always
