language: perl
perl:
    - "5.24"
    - "5.22"
    - "5.20"
env:
    global:
        - DEV_TESTING=1
        - PERL_CPANM_OPT="--quiet --notest --skip-satisfied"
addons:
    apt:
        packages:
            - aspell
            - aspell-en
before_script:
    - sudo mkdir -p /etc/portage /usr/portage /usr/local/portage /usr/share/portage/config
    - sudo chown $USER:$USER /etc/portage /usr/portage /usr/local/portage /usr/share/portage/config
    - cp t/data/etc/portage/make.conf /etc/portage/make.conf
    - wget "https://raw.githubusercontent.com/gentoo/portage/master/cnf/make.globals" -O /usr/share/portage/config/make.globals
    - wget "http://distfiles.gentoo.org/snapshots/portage-latest.tar.xz" -O /tmp/portage-latest.tar.xz
    - tar xJf /tmp/portage-latest.tar.xz -C /usr/
    - cpanm Test::CPAN::Changes Test::CheckManifest Test::EOL Test::Spelling    # DEV_TESTING dependency
after_success:
    - cpanm Devel::Cover::Report::Coveralls
    - cover -test -report coveralls
notifications:
    irc: "chat.freenode.net#gentoo-perl"
    on_success: change
    on_failure: always
